cargo-features = ["profile-rustflags"]

[package]
name        = "winnoisegen"
version     = "0.1.0"
authors     = ["Kaem <kaemviotto@icloud.com>"]
edition     = "2024"
description = "Create constant rain noise from the tray"
build       = "build.rs"

[dependencies]
anyhow             = "1"
cpal               = "0.18"
image              = { version = "0.25", default-features = false, features = ["png", "rayon"] }
qoaudio            = { git = "https://github.com/rafaelcaricio/qoaudio.git" }
ringbuf            = "0.5"
scopeguard         = "1"
tracing            = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
tray-icon          = { version = "0.25", default-features = false }
windows            = {
	version  = "0.62",
	features = [
		"Win32_System_Registry",
		"Win32_UI_WindowsAndMessaging",
	]
}

[dev-dependencies]
hound = "3.5"

[build-dependencies]
winresource = "0.1"

[profile.release]
lto           = "fat"
panic         = "abort"
codegen-units = 1
rustflags     = ["-C", "target-cpu=native"]
